
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    role: test-ha
spec:
  replicas: 2
  template:
    metadata:
      labels:
        role: test-ha
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
